(()=>{"use strict";
const K="boatbuilder.currentEstimate.v5",OLD=["boatbuilder.currentEstimate.v4","boatbuilder.currentEstimate.v3","boatbuilder.currentEstimate.v2","boatbuilder.currentEstimate.v1"],MC=new Set(["main-motors","kickers"]),SC=new Set(["electronics","electrical"]),SL=new Set(["Length","Beam","Chine / Bottom Width","Dry Hull Weight","Max / Bow Depth","Cockpit / Interior Depth","Deadrise","Transom Height","Transom Width","Max HP","Persons","Capacity Weight","Fuel Capacity","Bottom Thickness","Side / Freeboard Thickness","Construction"]),TR=[{id:"standard",label:"Standard factory / generic trailer included",low:0,high:0},{id:"premium-single",label:"Premium single axle",low:400,high:1200},{id:"galvanized-single",label:"Galvanized single axle",low:700,high:1600},{id:"aluminum-single",label:"Aluminum single axle",low:1200,high:2500},{id:"tandem",label:"Tandem axle",low:1500,high:3000},{id:"tandem-premium",label:"Premium tandem / aluminum",low:2500,high:4500}],E={app:document.querySelector("#app"),loading:document.querySelector("#loading"),back:document.querySelector("#back-button"),home:document.querySelector("#home-button"),clear:document.querySelector("#clear-estimate-button"),estimate:document.querySelector("#estimate-button"),count:document.querySelector("#estimate-count"),range:document.querySelector("#estimate-range")},M=new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:0});let C,B,S=load(),P=new Map,H=[];
const cl=v=>v==null?"":String(v).trim(),esc=v=>cl(v).replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;"),dm=i=>new Map((i.details||[]).map(d=>[d.label,d.value])),cfg=v=>({generationId:cl(v?.generationId)||null,era:cl(v?.era)||null,hp:Number(v?.hp)>0?Number(v.hp):null,trailer:cl(v?.trailer)||"standard"});
function load(){for(const k of[K,...OLD])try{const x=JSON.parse(localStorage.getItem(k)||"null");if(Array.isArray(x))return new Map(x.map(e=>typeof e==="string"?[e,cfg()]:[e.id,cfg(e)]))}catch{}return new Map()}
function save(){localStorage.setItem(K,JSON.stringify([...S].map(([id,c])=>({id,...cfg(c)}))));E.count.textContent=S.size;E.clear.disabled=!S.size;head()}
function eras(i){return Array.isArray(i.valueEras)?i.valueEras.map(v=>({label:v.label,low:v.lowPrice,high:v.highPrice,basis:v.basis||"Used complete-package screening estimate"})):[]}
function span(i){return cl(dm(i).get("Model Years / Era"))||cl(i.subtitle)||"Production years not established"}
function risk(i){return /varies|representative|multiple distinct|multiple generations|exact year|by year|redesign|audit pending/i.test(span(i))}
function specs(i){return Object.fromEntries((i.details||[]).filter(d=>SL.has(d.label)).map(d=>[d.label,{value:d.value,confidence:"catalog-representative"}]))}
function gens(i){if(i.categoryId!=="boats")return[];if(Array.isArray(i.designGenerations)&&i.designGenerations.length)return i.designGenerations.map(g=>({...g,basis:g.specificationBasis||g.basis||"",specs:g.catalogSpecs?specs(i):g.specs}));return[{id:i.id+":catalog",label:risk(i)?"Catalog specification basis, redesign audit pending":"Catalog specification basis",status:risk(i)?"generation-audit-required":"single-record-basis",basis:span(i)+(risk(i)?". The app has not verified that this design stayed unchanged across the full span.":". No conflicting design generation is currently documented."),specs:specs(i),eras:eras(i),synthetic:true}]}
function gen(i,c){const g=gens(i);return g.length===1?g[0]:g.find(x=>x.id===c.generationId)||null}
function eraList(i,c){const g=gen(i,c);if(!g)return[];return(g.eras?.length?g.eras:(g.synthetic||g.catalogSpecs?eras(i):[]))}
function price(i,c0={}){const c=cfg(c0),g=gen(i,c),a=eraList(i,c).find(x=>x.label===c.era);let p;if(i.categoryId==="boats"&&gens(i).length>1&&!g)p={low:null,high:null,basis:"Choose hull generation"};else if(i.categoryId==="boats"&&eraList(i,c).length&&!a)p={low:null,high:null,basis:"Choose age / era",generation:g};else if(a&&Number.isFinite(a.low)&&Number.isFinite(a.high))p={low:a.low,high:a.high,basis:a.basis,generation:g,era:a.label};else if(i.categoryId==="boats"&&g&&!g.synthetic)p={low:null,high:null,basis:a?.basis||"Generation-specific pricing pending",generation:g};else p={low:i.lowPrice,high:i.highPrice,basis:i.priceBasis,generation:g};if(i.categoryId==="boats"){const t=TR.find(x=>x.id===c.trailer)||TR[0];p.low=Number.isFinite(p.low)?p.low+t.low:p.low;p.high=Number.isFinite(p.high)?p.high+t.high:p.high;p.trailer=t}return p}
const fp=v=>Number.isFinite(v)?M.format(v):"Not set",fr=p=>Number.isFinite(p.low)&&Number.isFinite(p.high)?fp(p.low)+"–"+fp(p.high):"Price pending",work=id=>cfg(S.get(id)||P.get(id)||{});
function missing(i,c0={}){const c=cfg(c0),m=[];if(gens(i).length>1&&!c.generationId)m.push("hull generation");if(eraList(i,c).length&&!c.era)m.push("age / era");return m}
function setc(id,patch){const n=cfg({...work(id),...patch});if("generationId"in patch)n.era=null;P.set(id,n);if(S.has(id)){const i=B.get(id);missing(i,n).length?S.delete(id):S.set(id,n)}save()}
function controls(i,c,p){let x="",g=gens(i);if(g.length>1)x+=`<label class="config-field"><span>Hull generation</span><select data-g="${esc(i.id)}" id="${p}-g"><option value="">Choose hull generation</option>${g.map(v=>`<option value="${esc(v.id)}"${v.id===c.generationId?" selected":""}>${esc(v.label)}</option>`).join("")}</select><small>Hull design affects specifications and price.</small></label>`;const a=eraList(i,c);if(a.length)x+=`<label class="config-field"><span>Age / era</span><select data-a="${esc(i.id)}" id="${p}-a"><option value="">Choose age / era</option>${a.map(v=>`<option value="${esc(v.label)}"${v.label===c.era?" selected":""}>${esc(v.label)} · ${Number.isFinite(v.low)?fp(v.low)+"–"+fp(v.high):"pricing pending"}</option>`).join("")}</select></label>`;if(i.categoryId==="boats")x+=`<label class="config-field"><span>Trailer included</span><select data-t="${esc(i.id)}">${TR.map(v=>`<option value="${v.id}"${v.id===c.trailer?" selected":""}>${esc(v.label)}</option>`).join("")}</select></label>`;return x?`<div class="configuration-controls">${x}</div>`:""}
function panel(i,c){if(i.categoryId!=="boats")return"";const g=gen(i,c),w=i.generationWarning||(g?.status==="generation-audit-required"?"Specs are representative of the cited source, not guaranteed for every production year.":"");const r=g?Object.entries(g.specs||{}).map(([k,v])=>`<div class="definition-row"><dt>${esc(k)}</dt><dd>${esc(v.value)}${v.confidence?" · "+esc(v.confidence):""}</dd></div>`).join(""):"";return`<aside class="manufacturer-note">${w?`<strong>Generation warning:</strong> ${esc(w)}`:""}${g?`<p><strong>${esc(g.label)}</strong><br>${esc(g.basis)}</p>${r?`<dl class="definition-list">${r}</dl>`:""}`:""}</aside>`}
function bind(i,rer){E.app.querySelectorAll("[data-g]").forEach(s=>s.onchange=e=>{if(s.dataset.g===i.id){setc(i.id,{generationId:e.target.value||null});rer()}});E.app.querySelectorAll("[data-a]").forEach(s=>s.onchange=e=>{if(s.dataset.a===i.id){setc(i.id,{era:e.target.value||null});rer()}});E.app.querySelectorAll("[data-t]").forEach(s=>s.onchange=e=>{if(s.dataset.t===i.id){setc(i.id,{trailer:e.target.value});rer()}})}
const heading=(t,d="")=>`<header class="page-heading"><h1>${esc(t)}</h1>${d?`<p>${esc(d)}</p>`:""}</header>`,items=(c,s=null)=>C.items.filter(i=>i.categoryId===c&&(!s||i.subtypeId===s));
function route(){const p=location.hash.replace(/^#/,"").split("/");if(!p[0])return{v:"cats"};if(p[0]==="category")return{v:SC.has(decodeURIComponent(p[1]))?"subs":"makers",c:decodeURIComponent(p[1])};if(p[0]==="subtype")return{v:"makers",c:decodeURIComponent(p[1]),s:decodeURIComponent(p[2])};if(p[0]==="manufacturer")return{v:"list",c:decodeURIComponent(p[1]),s:SC.has(decodeURIComponent(p[1]))?decodeURIComponent(p[2]):null,m:decodeURIComponent(p.slice(SC.has(decodeURIComponent(p[1]))?3:2).join("/"))};if(p[0]==="item")return{v:"detail",id:decodeURIComponent(p.slice(1).join("/"))};if(p[0]==="estimate")return{v:"estimate"};return{v:"cats"}}
function nav(h){H.push(route());location.hash=h}function cats(){E.app.innerHTML=heading("Build a used aluminum outboard boat package","Choose the type of item.")+`<section class="card-list category-grid">${C.categories.sort((a,b)=>a.order-b.order).map(c=>`<button class="nav-card" data-c="${c.id}"><span><strong>${esc(c.name)}</strong><small>${items(c.id).length} catalog items</small></span></button>`).join("")}</section>`;E.app.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>nav("category/"+b.dataset.c))}
function subs(r){const g=new Map;for(const i of items(r.c)){const id=i.subtypeId||"other";if(!g.has(id))g.set(id,{id,name:i.subtypeName||"Other",n:0});g.get(id).n++}E.app.innerHTML=heading(C.categories.find(x=>x.id===r.c)?.name||r.c)+`<section class="card-list">${[...g.values()].map(x=>`<button class="nav-card" data-s="${x.id}"><strong>${esc(x.name)}</strong><small>${x.n} items</small></button>`).join("")}</section>`;E.app.querySelectorAll("[data-s]").forEach(b=>b.onclick=()=>nav(`subtype/${r.c}/${b.dataset.s}`))}
function makers(r){const g=new Map;for(const i of items(r.c,r.s))g.set(i.manufacturer,(g.get(i.manufacturer)||0)+1);E.app.innerHTML=heading("Choose a manufacturer")+`<section class="card-list">${[...g].sort().map(([m,n])=>`<button class="nav-card" data-m="${esc(m)}"><strong>${esc(m)}</strong><small>${n} models</small></button>`).join("")}</section>`;E.app.querySelectorAll("[data-m]").forEach(b=>b.onclick=()=>nav(`manufacturer/${r.c}/${r.s?r.s+"/":""}${encodeURIComponent(b.dataset.m)}`))}
function list(r){const a=items(r.c,r.s).filter(i=>i.manufacturer===r.m).sort((a,b)=>a.model.localeCompare(b.model));E.app.innerHTML=heading(r.m)+(r.c==="boats"?`<aside class="manufacturer-note"><strong>Generation audit:</strong> Every model identifies its specification basis. Broad spans remain flagged until redesign boundaries are verified.</aside>`:"")+`<section class="card-list">${a.map(i=>`<article class="item-card"><button class="item-open" data-i="${esc(i.id)}"><strong>${esc(i.model)}</strong><span>${esc(i.subtitle||"")}${risk(i)?" · generation audit pending":""}</span></button><span class="price">${fr(price(i,work(i.id)))}</span></article>`).join("")}</section>`;E.app.querySelectorAll("[data-i]").forEach(b=>b.onclick=()=>nav("item/"+encodeURIComponent(b.dataset.i)))}
function detail(r){const i=B.get(r.id);if(!i)return cats();const c=work(i.id),p=price(i,c),ok=!missing(i,c).length;E.app.innerHTML=`<article class="detail-card"><div class="detail-body"><h1>${esc(i.displayName)}</h1>${controls(i,c,"d")}${panel(i,c)}<div class="detail-select"><label><input id="pick" type="checkbox" ${S.has(i.id)?"checked":""} ${!S.has(i.id)&&!ok?"disabled":""}> Add to estimate</label><strong>${fr(p)}</strong></div>${!ok?`<p class="selection-requirement">Choose ${missing(i,c).join(" and ")} before adding.</p>`:""}<div class="price-panel"><div class="price-box"><small>Low</small><strong>${fp(p.low)}</strong></div><div class="price-box"><small>High</small><strong>${fp(p.high)}</strong></div></div><p class="data-note">${esc(p.basis||i.priceBasis||"")}</p><dl class="definition-list">${(i.details||[]).map(d=>`<div class="definition-row"><dt>${esc(d.label)}</dt><dd>${esc(d.value)}</dd></div>`).join("")}</dl></div></article>`;document.querySelector("#pick").onchange=e=>{e.target.checked?S.set(i.id,c):S.delete(i.id);save();detail(r)};bind(i,()=>detail(r))}
function estimate(){const a=[...S].map(([id,c])=>({i:B.get(id),c,p:price(B.get(id),c)})).filter(x=>x.i),lo=a.reduce((s,x)=>s+(x.p.low||0),0),hi=a.reduce((s,x)=>s+(x.p.high||0),0);E.app.innerHTML=heading("Current estimate")+`<section class="estimate-summary"><div><small>Package low</small><strong>${fp(lo)}</strong></div><div><small>Package high</small><strong>${fp(hi)}</strong></div></section><section class="card-list">${a.map(x=>`<article class="estimate-line"><input type="checkbox" data-r="${esc(x.i.id)}" checked><div><h2>${esc(x.i.displayName)}</h2>${controls(x.i,cfg(x.c),"e")}${fr(x.p)}</div></article>`).join("")}</section>`;E.app.querySelectorAll("[data-r]").forEach(b=>b.onchange=()=>{S.delete(b.dataset.r);save();estimate()});for(const x of a)bind(x.i,estimate)}
function head(){let l=0,h=0,n=0;for(const[id,c]of S){const p=price(B.get(id),c);if(Number.isFinite(p.low)){l+=p.low;h+=p.high}else n++}E.range.textContent=S.size?(n?"Price pending":fp(l)+"–"+fp(h)):"$0"}
function render(){const r=route();E.back.hidden=r.v==="cats";({cats,subs,makers,list,detail,estimate}[r.v]||cats)(r);E.app.hidden=false}
function init(){C=window.BOATBUILDER_DATA;if(!C?.items?.length)throw Error("Catalog missing");B=new Map(C.items.map(i=>[i.id,i]));S=new Map([...S].filter(([id,c])=>B.has(id)&&!missing(B.get(id),c).length));save();E.loading.hidden=true;render()}
E.back.onclick=()=>{const r=H.pop();r?history.back():nav("")};E.home.onclick=()=>nav("");E.clear.onclick=()=>{S.clear();save();render()};E.estimate.onclick=()=>nav("estimate");onhashchange=render;try{init()}catch(e){console.error(e);E.loading.innerHTML="<strong>The catalog could not be loaded.</strong>"}
})();
